name: bodhi-infra-prod-main
version: 1

source:
  provider: GitHub
  properties:
    branch: main
    repository: https://github.com/shunjizhan/bodhi-infra-prod

stages:
  - name: dev
    requires_approval: false
    deployments:
      subql-node-karura:
      subql-node-acala:
    test_commands:
      - echo "woo! Tests passed"

